import { ListingDraft } from '../../types/draft';

export class GoogleChatCards {
  /**
   * Generates an interactive preview card for the listing draft.
   */
  static buildListingPreviewCard(draft: ListingDraft): any {
    const aspectSummary = Object.entries(draft.aspects || {})
      .slice(0, 5)
      .map(([k, v]) => `<b>${k}:</b> ${Array.isArray(v) ? v.join(', ') : v}`)
      .join('<br>');

    const imageUrl = draft.imageUrls && draft.imageUrls.length > 0 ? draft.imageUrls[0] : null;

    const sections: any[] = [];

    // Image section
    if (imageUrl) {
      const imageWidgets: any[] = [
        {
          image: {
            imageUrl: imageUrl,
            altText: draft.title,
          },
        },
      ];

      if (draft.imageUrls.length > 1) {
        imageWidgets.push({
          decoratedText: {
            topLabel: 'eBay Photo Gallery',
            text: `📸 <b>${draft.imageUrls.length} photos ready</b> (1 primary + ${draft.imageUrls.length - 1} gallery photos)`,
            wrapText: true,
          },
        });
      }

      sections.push({
        widgets: imageWidgets,
      });
    }

    // Details section
    sections.push({
      header: 'Listing Overview',
      widgets: [
        {
          decoratedText: {
            topLabel: 'Title (80 chars max)',
            text: `<b>${draft.title}</b>`,
            wrapText: true,
          },
        },
        {
          decoratedText: {
            topLabel: 'Suggested Price',
            text: `<font color="#188038"><b>$${draft.price.toFixed(2)} ${draft.currency}</b></font>`,
          },
        },
        {
          decoratedText: {
            topLabel: 'Category',
            text: draft.categoryName || draft.categoryId || 'General',
          },
        },
        {
          decoratedText: {
            topLabel: 'Condition',
            text: `${draft.condition} ${draft.conditionDescription ? `(${draft.conditionDescription})` : ''}`,
            wrapText: true,
          },
        },
        {
          decoratedText: {
            topLabel: 'Shipping & Returns',
            text: `🚚 <b>${!draft.shippingCost || draft.shippingCost <= 0 ? 'FREE Shipping' : `$${draft.shippingCost.toFixed(2)} Shipping`}</b> (USPS, 3-day handling) • <b>No Returns</b>`,
            wrapText: true,
          },
        },
        ...(aspectSummary
          ? [
              {
                decoratedText: {
                  topLabel: 'Key Aspects',
                  text: aspectSummary,
                  wrapText: true,
                },
              },
            ]
          : []),
      ],
    });

    const publishUrl = `https://ebay-chat-agent.tommyguc.workers.dev/publish?draftId=${encodeURIComponent(draft.id)}&spaceId=${encodeURIComponent(draft.spaceId)}&threadKey=${encodeURIComponent(draft.threadKey)}`;
    const isFreeShipping = !draft.shippingCost || draft.shippingCost <= 0;
    const priceDisplay = isFreeShipping
      ? `$${draft.price.toFixed(2)} (Free Ship)`
      : `$${draft.price.toFixed(2)} + $${draft.shippingCost!.toFixed(2)} ship`;

    // Action buttons section
    sections.push({
      widgets: [
        {
          buttonList: {
            buttons: [
              {
                text: `🚀 Publish to eBay (${priceDisplay})`,
                onClick: {
                  openLink: {
                    url: publishUrl,
                  },
                },
              },
            ],
          },
        },
        {
          textParagraph: {
            text: '💡 <i>Tip: Tap the button above, or simply reply <b>"publish it"</b> to publish to eBay! (e.g. "change price to $20", "set shipping to $5")</i>',
          },
        },
      ],
    });

    return {
      cardsV2: [
        {
          cardId: `draft-card-${draft.id}`,
          card: {
            header: {
              title: '🏷️ eBay Listing Draft',
              subtitle: 'Generated by Gemini Vision',
              imageUrl: 'https://ebay-chat-agent.tommyguc.workers.dev/avatar.png',
              imageType: 'SQUARE',
            },
            sections,
          },
        },
      ],
    };
  }

  /**
   * Card rendered when listing is published successfully.
   */
  static buildPublishedSuccessCard(draft: ListingDraft, listingUrl: string, listingId: string): any {
    return {
      cardsV2: [
        {
          cardId: `success-card-${draft.id}`,
          card: {
            header: {
              title: '🎉 Listing Live on eBay!',
              subtitle: `Item ID: ${listingId}`,
              imageUrl: 'https://ebay-chat-agent.tommyguc.workers.dev/avatar.png',
              imageType: 'CIRCLE',
            },
            sections: [
              {
                widgets: [
                  ...(draft.imageUrls && draft.imageUrls.length > 0
                    ? [
                        {
                          image: {
                            imageUrl: draft.imageUrls[0],
                            altText: draft.title,
                          },
                        },
                      ]
                    : []),
                  {
                    decoratedText: {
                      topLabel: 'Title',
                      text: `<b>${draft.title}</b>`,
                      wrapText: true,
                    },
                  },
                  {
                    decoratedText: {
                      topLabel: 'Listed Price',
                      text: `<b>$${draft.price.toFixed(2)} ${draft.currency}</b> (${!draft.shippingCost || draft.shippingCost <= 0 ? 'FREE Shipping' : `+$${draft.shippingCost.toFixed(2)} Shipping`}) • <b>No Returns</b>`,
                    },
                  },
                  ...(draft.imageUrls && draft.imageUrls.length > 1
                    ? [
                        {
                          decoratedText: {
                            topLabel: 'eBay Photo Gallery',
                            text: `📸 <b>${draft.imageUrls.length} photos published</b> to eBay listing`,
                          },
                        },
                      ]
                    : []),
                  {
                    buttonList: {
                      buttons: [
                        {
                          text: '🔗 View on eBay',
                          onClick: {
                            openLink: {
                              url: listingUrl,
                            },
                          },
                        },
                      ],
                    },
                  },
                ],
              },
            ],
          },
        },
      ],
    };
  }

  /**
   * Card rendered on error.
   */
  static buildErrorCard(errorMessage: string): any {
    return {
      cardsV2: [
        {
          cardId: `error-card-${Date.now()}`,
          card: {
            header: {
              title: '⚠️ Action Failed',
              subtitle: 'eBay Listing Agent',
            },
            sections: [
              {
                widgets: [
                  {
                    textParagraph: {
                      text: `<font color="#c5221f">${errorMessage}</font>`,
                    },
                  },
                ],
              },
            ],
          },
        },
      ],
    };
  }
}
